### PR TITLE
Downgrade record processing logging to reduce noise

### PR DESCRIPTION
**Pull request by darrenmc**

### CODE REVIEW

**Comment by jlogeart** [comment]
@darrenmc Can you document how the proportion of those metrics vs everything else?
Are we saving much by doing this change?

**Comment by darrenmc** [comment]
@jlogeart looking at the last 7 days for the top log producers:
```
Source              Kinesis
Beacon                   1%
Shopify jobs             8%
Ratecard                 0%
Harmonization engine    22%
Fraud                   49%
Feed                    92%
Order management        76%
Tracking                46%
Export                  86%
```

I've excluded other top producers that do not consume events such as proxy an the api services

**Comment by jlogeart** [comment]
@darrenmc If we make that change, what is the impact in terms of overall logs saved?

This trace is generally useful to track the speed of consumption.

**Comment by darrenmc** [comment]
@jlogeart I did not know that this logging was being used for any meaningful metrics. Given that it is used then it does not seem worth removing the logging.

The kinesis logging accounts for ~9% of the log volume. 

Proxy and beacon are the largest log producers with a combined total of ~50% of the total log volume (and do not have any meaningful Kinesis impact)

**Pull request closed without merging**
